### ISSUE TITLE
web page freezing problem when trying to convert long html documents

### ISSUE THREAD

**Issue by repomorphic** [asciidocfx/to-asciidoc#3]
Hello. I am trying to convert java specification to asciidoc format. I downloaded and copy all of the HTML and paste input. (https://docs.oracle.com/javase/specs/jls/se10/html/jls-1.html) When I click convert button on firefox browser my page freeze and I get the following message:
Firefox a web page is slowing down your browser "Stop it" "Wait"
How can I fix this problem?

**Comment by rahmanusta** [comment]
Hi @lostdinar2 , it is possible for huge content. I could suggest to use webworker but this plugin  access to DOM.

**Comment by repomorphic** [comment]
Thanks, now it works.
